# Generated by Django 4.1.4 on 2022-12-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_description_product_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
    ]
